### PR TITLE
Revert "Lazy-Hand: Branch sync: SPRC-1713 witheejdwdedddfff

### PR DESCRIPTION
**Pull request by ankur17**
Reverts ankur17/testrepo#12

### CODE REVIEW

**Comment by ankur17** [comment]
@lazu-hand: merge now

**Comment by ankur17** [comment]
@lazu-hand: merge now

**Comment by ankur17** [comment]
this is another comment

**Comment by ankur17** [comment]
sfdkmvkld

**Comment by ankur17** [comment]
dflmlk

**Comment by ankur17** [comment]
acsadsc

**Comment by ankur17** [comment]
sac

**Comment by ankur17** [comment]
yellow

**Comment by ankur17** [comment]
besting

**Review by ankur17 — COMMENTED** [review]
IS THIS WORKING WELL

**Review by ankurnoob — CHANGES_REQUESTED** [review]
what is this?

**Review by ankurnoob — CHANGES_REQUESTED** [review]
Again wrong

**Review by ankurnoob — APPROVED** [review]
LgTM

**Review by ankurnoob — CHANGES_REQUESTED** [review]
baddddd

**Comment by ankurnoob** [comment]
going good

**Comment by ankurnoob** [comment]
yess

**Review by ankurnoob — COMMENTED** [review]
this is not looking good

**Review by ankurnoob — CHANGES_REQUESTED** [review]
gggg

**Comment by ankur17** [comment]
this is working

**Review by ankur17 — COMMENTED** [review]
Added as a review comment

**Review by ankurspringworks — APPROVED** [review]

**Review by ankurnoob — APPROVED** [review]

**Review by ankurnoob — APPROVED** [review]

**Review by ankurnoob — APPROVED** [review]

**Review by ankurnoob — APPROVED** [review]

**Review by ankurnoob — APPROVED** [review]

**Review by ankurnoob — APPROVED** [review]

**Review by ankurnoob — APPROVED** [review]

**Review by ankurnoob — APPROVED** [review]

**Pull request merged**
